name: rickgabrielly
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#653235'
    - '#67000a'
    - '#aa6a19'
    - '#f1f7b0'
  brandStrength: 0.4375
  lightness: 0.7032361312303692
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
