name: rickgabrielly
favicon: null
layout_spectrum: 0.8176410649903119
typography_spectrum: 0.08071362832561135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.31329686008393764
  lightness: 0.7032361312303692
  saturation: 0.3557573459111154
  rhythmicContrast: 0.2471228630747646
purpose: []
